---
- name: Install and configure SonarQube
  hosts: localhost
  become: yes

  tasks:
    - name: Install Java 8 (Amazon Corretto)
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - java-1.8.0-amazon-corretto
        - java-1.8.0-amazon-corretto-devel

    - name: Download SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.6.zip
        dest: /opt/sonarqube-7.6.zip

    - name: Unzip SonarQube
      unarchive:
        src: /opt/sonarqube-7.6.zip
        dest: /opt
        remote_src: yes

    - name: Create sonar group
      group:
        name: sonar
        state: present

    - name: Create sonar user
      user:
        name: sonar
        comment: "Sonar System User"
        home: /opt/sonarqube-7.6
        group: sonar
        shell: /bin/bash
        state: present

    - name: Set ownership for SonarQube directory
      file:
        path: /opt/sonarqube-7.6
        owner: sonar
        group: sonar
        recurse: yes

    - name: Set permissions for SonarQube directory
      file:
        path: /opt/sonarqube-7.6
        mode: '0775'
        recurse: yes

    - name: Modify sonar.sh to run as sonar user
      lineinfile:
        path: /opt/sonarqube-7.6/bin/linux-x86-64/sonar.sh
        regexp: '^#RUN_AS_USER='
        line: 'RUN_AS_USER=sonar'

    - name: Create SonarQube systemd service file
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target
          [Service]
          Type=forking
          ExecStart=/opt/sonarqube-7.6/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube-7.6/bin/linux-x86-64/sonar.sh stop
          User=sonar
          Group=sonar
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Start SonarQube service
      service:
        name: sonarqube
        state: started
        enabled: yes

    - name: Create userdata completion marker
      file:
        path: /userdata.complete
        state: touch