---
- name: Install and configure HashiCorp Vault
  hosts: localhost  # Replace with your target hosts or groups
  become: yes       # Ensure the playbook runs with elevated privileges

  tasks:
    - name: Ensure prerequisites are installed
      package:
        name:
          - unzip
          - wget
        state: present

    - name: Download Vault binary
      get_url:
        url: "https://releases.hashicorp.com/vault/1.11.0/vault_1.11.0_linux_amd64.zip"
        dest: /tmp/vault.zip

    - name: Unzip Vault binary
      unarchive:
        src: /tmp/vault.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Set Vault binary permissions
      file:
        path: /usr/local/bin/vault
        mode: '0755'

    - name: Create Vault configuration directory
      file:
        path: /etc/vault.d
        state: directory

    - name: Create Vault configuration file
      copy:
        dest: /etc/vault.d/vault.hcl
        content: |
          storage "file" {
            path = "/opt/vault/data"
          }
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_disable = 1
          }
          ui = true

    - name: Create Vault systemd service file
      copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description=HashiCorp Vault
          Documentation=https://www.vaultproject.io/docs/
          After=network-online.target
          Wants=network-online.target

          [Service]
          User=vault
          Group=vault
          ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
          ExecReload=/bin/kill --signal HUP $MAINPID
          KillSignal=SIGINT
          Restart=on-failure
          LimitNOFILE=8192
          TimeoutSec=30

          [Install]
          WantedBy=multi-user.target

    - name: Create Vault user and group
      user:
        name: vault
        state: present

    - name: Create Vault data directory
      file:
        path: /opt/vault/data
        state: directory
        owner: vault
        group: vault
        mode: '0700'

    - name: Enable and start Vault service
      systemd:
        name: vault
        state: started
        enabled: yes

    - name: Check Vault service status
      command: systemctl status vault
      register: vault_status

    - name: Debug Vault service status
      debug:
        msg: "Vault service status: {{ vault_status.stdout }}"
